dwc3993/CS312_Graphics

coursefunctions.h
definitions.h
pipeline.cpp

Got a small red dot to show up on the screen!

Dane Christensen Project 01 - drawPoint

---

coursefunctions.h
definitions.h
pipeline.cpp

Got the red dot to show up! Thanks for all the help Bro. Christensen!

Nathan Tagg Project 01 - drawPoint

---

coursefunctions.h
definitions.h
pipeline.cpp

Matthew Brown Project 01 - drawPoint

---

coursefunctions.h
definitions.h
pipeline.cpp

<p> Got a small red dot to show up on the screen! </p>

Justin Chandler Project 01 - drawPoint

---

coursefunctions.h
definitions.h
pipeline.cpp

Sean Conley Project 01 - drawPoint

---

coursefunctions.h
definitions.h
pipeline.cpp

Drew a red pixel on the upper left corner.

Zach Newell - Project 01 - drawpoint

---

coursefunctions.h
definitions.h
pipeline.cpp

Wyatt Larson Project 01 - drawPoint

---

.vscode/launch.json
coursefunctions.h
definitions.h
pipeline.cpp

Tyler Starr Project01 - drawPoint

---

coursefunctions.h
definitions.h
pipeline.cpp

Tyler Elkington Project 01 - drawPoint

---

coursefunctions.h
definitions.h
pipeline.cpp

Steven Wilde Project 01 - drawPoint

---

coursefunctions.h
definitions.h
pipeline.cpp

Red pixel is visible in the top left corner.
This commit also includes the changes for the team activity.

Quade Morrison Project 01 - drawPoint

---

coursefunctions.h
definitions.h
pipeline.cpp

A small red dot was printed in the top left corner

James Thomas Project 01 - drawPoint

---

coursefunctions.h
definitions.h
pipeline.cpp

Dylan Doelling Project 01 - drawPoint

---

coursefunctions.h
definitions.h
pipeline.cpp

Caleb Hensley Project 01 - drawPoint

---

coursefunctions.h
definitions.h
pipeline.cpp

Curtis Wakley Project 01- drawPoint

---

coursefunctions.h
definitions.h
pipeline.cpp

picture of the red corner dot.

Andrew Shore Project 01 - drawPoint

---

coursefunctions.h
definitions.h
pipeline.cpp

Luc Comeau Project 01 - drawPoint

---

coursefunctions.h
definitions.h
pipeline.cpp

Jake Schwantes Project 01 - drawPoint

---

coursefunctions.h
definitions.h
pipeline.cpp

Got the red dot to appear on the top left of the application! Also some merge conflicts have been corrected.

Benson Norman Project 01 - drawPoint

---

coursefunctions.h
definitions.h
pipeline.cpp

Jeremy Chandler Project 01 - drawPoint

---

coursefunctions.h
definitions.h
pipeline.cpp

Ben Fisher Project 01 - drawPoint

---

coursefunctions.h
definitions.h
pipeline.cpp

Tyler Brown Project 01 - drawPoint

---

.gitignore
coursefunctions.h
definitions.h
pipeline.cpp

Braden Brown Project 01 - drawPoint

---

coursefunctions.h
pipeline.cpp

Added triangle drawing with Barycentric fill

[Project 02] Alex Charles - Triangle Drawing

---

coursefunctions.h
definitions.h
pipeline.cpp
utilitiesfunctions.h

Draws the six triangles and the correct colors for each one.

​[Project 02] Benson Norman - Triangle Drawing​

---

coursefunctions.h
pipeline.cpp

There are imperfections - for example, the upper green triangle has some "teeth" on the left edge

[Project 02] Tyler Starr - Triangle Drawing

---

coursefunctions.h
pipeline.cpp

Completed Triangle Rasterization.

[Project 02] Tyler Elkington - Triangle Drawing

---

coursefunctions.h
pipeline.cpp

[Project 02] Wyatt Larson - Triangle Drawing

---

coursefunctions.h
definitions.h
pipeline.cpp

[Project 02] Nathan Prestwich - Triangle Drawing

---

coursefunctions.h
pipeline.cpp

Draws triangles based on the given vertices.

[Project 02] Darren Kersey - Triangle Drawing

---

.gitignore
coursefunctions.h
pipeline.cpp

Triangle Rasterization using the Barycentric Algorithm

Zach Newell - 02 - Triangle Rasterization

---

coursefunctions.h
pipeline.cpp

The main thing I learned from this exercise was to make sure I am comparing the right vertices.  I had to go back and double check that I was using the correct maxs, mins and such.

Scott Nicholes project 02 draw triangle

---

pipeline.cpp

Ben fisher project 02 triangle drawing

---

coursefunctions.h
pipeline.cpp

Jake Schwantes [Project 2] - Draw Triangles

---

coursefunctions.h
pipeline.cpp

Drew some triangles using the barycentric algorithm.
Here's how it works:
S and T represent the percentage of the triangle that we are trying to fill. In this case the cross product is just the determinant which is calculating the area of the point we're checking vs two of the triangles vertexes v1 and v2. This area is being divided by the area of the triangle formed by v1 and v2. Because the points are given to us in counter clock wise order, if the determinate is positive then the point is to the left of the edge vn and p, thus if S and T are positive the point is in the triangle.
The reason we don't have to check for v3 is because if S and T which represents the area of the main triangle that has been taken up, are less then 1 then we know that there is room for a 3rd triangle which is …

[Project 02] Quade Morrison - Triangle Drawing

---

coursefunctions.h
definitions.h
pipeline.cpp

Really hope I'm doing this right...

[Project 02] First Last - Triangle Drawing

---

coursefunctions.h
pipeline.cpp

Steven Wilde Project 02 - Triangle Drawing

---

coursefunctions.h
definitions.h
pipeline.cpp

Caleb Hensley Project 02 Triangle Drawing

---

coursefunctions.h
definitions.h
pipeline.cpp

[Project02]Paul_Owens- Triangle_Drawing

---

coursefunctions.h
definitions.h
pipeline.cpp

Really struggled with this week's project!

Christopher Wilson Project 02 - triangleRasterization

---

coursefunctions.h
pipeline.cpp

[Project 02] Matthew Brown - Triangle Drawing

---

coursefunctions.h
definitions.h
pipeline.cpp

Finished triangle function

---

coursefunctions.h
pipeline.cpp

[Project 02] Sean Conley - Triangle Drawing

---

coursefunctions.h
definitions.h
pipeline.cpp

Gwieland project02 draw triangle

---

.vscode/c_cpp_properties.json
coursefunctions.h
definitions.h
pipeline.cpp

Drawpixel and drawtriangle should be working. for some reason I can g++ but not run code. Will ask for help on this.

Draw pixel and triangle working

---

coursefunctions.h
definitions.h
pipeline.cpp
shaders.h

Jordan Parry Project 03 Fragment Shader

---

coursefunctions.h
definitions.h
pipeline.cpp
shaders.h

[Project 03] Nathan Prestwich - Linear Interpolation

---

coursefunctions.h
definitions.h
pipeline.cpp

Steven Wilde - Project 03 - Fragment shaders

---

coursefunctions.h
definitions.h
pipeline.cpp
utilitiesfunctions.h

Benson Norman Project 03 Linear Interpolation

---

coursefunctions.h
definitions.h
pipeline.cpp
shaders.h

[Dane Christensen] 03 project03 Frag Shaders 

---

coursefunctions.h
pipeline.cpp

[Project 05] Matthew Brown - Perspective Correction

---

coursefunctions.h
definitions.h
pipeline.cpp

[Project 04] Dylan Doelling - Perspective Correction

---

coursefunctions.h
definitions.h
pipeline.cpp

Completed the Perspective Correction!

[Project 04] Tyler Elkington - Perspective Correction

---

coursefunctions.h
definitions.h
pipeline.cpp

Preston Higgins Project04 Perspective Correction

---

coursefunctions.h
definitions.h
pipeline.cpp

Uses perspective correction calculations on a red and white checker board image.

Project 04 Darren Kersey - Perspective Correction

---

coursefunctions.h
definitions.h
pipeline.cpp

Wyatt Larson [Project 04 Perspective Correction]

---

coursefunctions.h
definitions.h
pipeline.cpp

[Project 04] Anthony Lasley - Perspective Correction

---

coursefunctions.h
definitions.h
pipeline.cpp

I shaded away all of the white values to be red but it still is the checker image.

Jacob Schwantes [Project 04] - Perspective correct

---

coursefunctions.h
definitions.h
pipeline.cpp

Tyler Starr Project 04 - perspectiveCorrection

---

coursefunctions.h
definitions.h
pipeline.cpp

James Thomas Project04 Perspective Correction

---

coursefunctions.h
definitions.h
pipeline.cpp

[Project 04] Curtis Wakley - Perspective Correction

---

coursefunctions.h
definitions.h
pipeline.cpp

[Project04_Submission.pdf](https://github.com/dwc3993/CS312_Graphics/files/2848473/Project04_Submission.pdf)

Project 04 Scott Nicholes - Perspective Correction

---

coursefunctions.h
pipeline.cpp

Zach Newell - project 04 - perspective correction

---

coursefunctions.h
definitions.h
pipeline.cpp

Andrew Shore Project04-Perspective

---

coursefunctions.h
definitions.h
pipeline.cpp

Finished perspective correction and modified attributes to store values in an array rather than single member variables!

[Project 04] Benson Norman - Perspective Correction

---

coursefunctions.h
definitions.h
pipeline.cpp

[Project 04] Quade Morrison - Perspective Correction

---

coursefunctions.h
pipeline.cpp

[Project 04] Nathan Prestwich - Perspective Correction

---

coursefunctions.h
definitions.h
pipeline.cpp

Ryan Budd: Project 04 Perspective Correct Interpolation

---

coursefunctions.h
definitions.h
pipeline.cpp

project04 perspective drawing

---

coursefunctions.h
definitions.h
pipeline.cpp

I added a few things on top of the requirements.

Ben Fisher Project 04 Perspective

---

coursefunctions.h
definitions.h
pipeline.cpp
shaders.h

[Project04]Paul_Owens-Perspective_Correction

---

coursefunctions.h
definitions.h
pipeline.cpp

[Project 04] Dane Christensen Perspective Correction

---

coursefunctions.h
definitions.h
pipeline.cpp
shaders.h

[Project 05] - Alex Charles - Implemented vertex shader and transformations

---

coursefunctions.h
definitions.h
pipeline.cpp

[Project 05] Quade Morrison - Vertex Shader & Transformations

---

coursefunctions.h
definitions.h
pipeline.cpp
shaders.h

Preston Higgins Project05 Vertex Shader and Transformations

---

coursefunctions.h
definitions.h
pipeline.cpp

[Project 5] James Thomas Vertex Shaders

---

coursefunctions.h
definitions.h
pipeline.cpp
shaders.h

[Project 05] Nathan Prestwich - Vertex Shader and Transformation

---

coursefunctions.h
definitions.h
pipeline.cpp

Andrew Shore P05 VertexShader

---

coursefunctions.h
definitions.h
pipeline.cpp
shaders.h

[Project 05] Tyler Elkington - Vertex Shader & Transformations

---

coursefunctions.h
definitions.h
pipeline.cpp

It draws stuff and rotates and all that stuff!
You mentioned that our results might not be exactly like the PDF. Is this still true?

[Project 05] Curtis Wakley - Vertex Shader & Transformations

---

coursefunctions.h
definitions.h
pipeline.cpp

Zach Newell - Project 05 - Vertex Shader and Transformations

---

coursefunctions.h
definitions.h
pipeline.cpp

[Project 05] Matthew Brown - Vertex Shader & Transformations

---

coursefunctions.h
definitions.h
fragment.fs
matrix.h
pipeline.cpp
shaders.h
vertex.vs

[Project 05] Wyatt Larson - Vertex Shaders

---

coursefunctions.h
definitions.h
pipeline.cpp

Alexander Bluhm Project 05 - Vertex Shader & Transformations

---

coursefunctions.h
definitions.h
pipeline.cpp
shaders.h

This project took considerably more effort than the previous ones and we had to collaborate to solve some of the problems that we encountered. Thanks to everybody who showed up to our meeting on Wednesday night.

Tyler Starr Project 05 - Vertex Shader

---

coursefunctions.h
definitions.h
pipeline.cpp

It's does vertex shading and transformations.

Darren Kersey Project 05 - Vertex Shader and Transformations

---

coursefunctions.h
definitions.h
pipeline.cpp

[Project 05] Steven Wilde - Vertex Shader and Transformations

---

coursefunctions.h
definitions.h
pipeline.cpp

[Project 05] Anthony Lasley - Vertex Shader & Transformations

---

coursefunctions.h
definitions.h
pipeline.cpp
shaders.h

[Project 06] Nathan Prestwich - Finished Pipeline

---

coursefunctions.h
definitions.h
pipeline.cpp

Setup the Matrix class and its helper functions. Defined the transformationVertexShader. Everything works fine except for the last triangle, I am not quite sure why.

Ryan Budd: Project05 Vertex Shader

---

coursefunctions.h
definitions.h
pipeline.cpp

The math actually worked, but I forgot to return it from the function!
